const {test}=require('node:test'),assert=require('node:assert/strict'),scan=require('../crop-scan.js');
const response={success:true,crop:[{name:'tomato',probability:.8}],diseases:[{name:'early blight',probability:.92,details:{symptoms:{Leaves:'Brown spots'},severity:'Can damage foliage',treatment:{prevention:['Avoid wet foliage']}}},{name:'Septoria leaf spot',probability:.06}]};
test('parses deployed proxy response and structured optional details',()=>{const r=scan.parse(response);assert.equal(r.crops[0].name,'tomato');assert.equal(r.diseases[0].probability,.92);assert.match(r.diseases[0].symptoms,/Leaves: Brown spots/);assert.match(r.diseases[0].treatment,/Avoid wet foliage/);assert.equal(r.diseases.length,2);});
test('supports raw response; sorts suggestions and handles missing optional details',()=>{const r=scan.parse({result:{disease:{suggestions:[{name:'other',probability:.1},{name:'healthy',probability:.9}]}}});assert.equal(r.healthy,true);assert.equal(r.diseases[0].symptoms,'');assert.deepEqual(r.crops,[]);});
test('missing or invalid confidence is unknown, never invented',()=>{for(const p of [null,undefined,'0.9',-1,95,NaN])assert.equal(scan.parse({crop:[{name:'tomato',probability:p}]}).crops[0].probability,null);assert.equal(scan.parse({crop:[{name:'tomato',probability:0}]}).crops[0].probability,0);});
test('rejects service errors, empty results, and non-plant photos',()=>{assert.throws(()=>scan.parse({success:false}),/scanServiceError/);assert.throws(()=>scan.parse({}),/scanNoMatch/);assert.throws(()=>scan.parse({...response,raw:{result:{is_plant:{binary:false}}}}),/scanNotPlant/);});
test('POST contains stripped base64 and public apikey, never a provider key or false JWT',async()=>{await scan.identify('data:image/jpeg;base64,YWJj',{url:'https://example.test',key:'sb_publishable_test',fetcher:async(url,options)=>{assert.equal(options.method,'POST');assert.deepEqual(JSON.parse(options.body),{image:'YWJj'});assert.deepEqual(options.headers,{'Content-Type':'application/json',apikey:'sb_publishable_test'});return {ok:true,json:async()=>response};}});});
test('HTTP and malformed JSON fail cleanly',async()=>{for(const status of [401,403,429,500])await assert.rejects(scan.identify('YWJj',{fetcher:async()=>({ok:false,status})}),/scan(Auth|Limit|Service)Error/);await assert.rejects(scan.identify('YWJj',{fetcher:async()=>({ok:true,json:async()=>{throw Error();}})}),/scanInvalidResponse/);});
test('timeout and cancellation abort the request',async()=>{const fetcher=(_,o)=>new Promise((resolve,reject)=>{const fail=()=>reject(new Error('abort'));if(o.signal.aborted)fail();else o.signal.addEventListener('abort',fail);});await assert.rejects(scan.identify('YWJj',{timeoutMs:5,fetcher}),/scanTimeout/);const c=new AbortController();const pending=scan.identify('YWJj',{signal:c.signal,fetcher});c.abort();await assert.rejects(pending,/scanCancelled/);});
test('tomato-only cases A–D and threshold boundaries',()=>{
 const fixture=(name,p,issue=.804)=>({crops:[{name,probability:p}],diseases:[{name:'Target Spot',probability:issue}]});
 assert.equal(scan.validateTomato(fixture('Tomato',.9),'tomato').accepted,true);
 const b=fixture('Tobacco',.006);assert.deepEqual(scan.validateTomato(b,'tomato'),{accepted:true,fallback:true});assert.equal(b.diseases[0].probability,.804);
 assert.equal(scan.validateTomato(fixture('Potato',.85),'tomato').reason,'unsupported');
 assert.equal(scan.validateTomato(fixture('Tobacco',.006,.1),'tomato').reason,'uncertain');
 assert.equal(scan.validateTomato(fixture('Potato',.6),'tomato').accepted,false);
 assert.equal(scan.validateTomato(fixture('Potato',.599),'tomato').accepted,true);
 assert.equal(scan.validateTomato(fixture('Tomato',.5)).accepted,true);
 assert.equal(scan.validateTomato(fixture('Tobacco',.006)).accepted,false);
 assert.equal(scan.validateTomato(fixture('Tomato',.9),'potato').accepted,false);
 assert.equal(scan.validateTomato(fixture('Tomato',.9,null),'tomato').accepted,false);
 assert.equal(scan.validateTomato({crops:[],diseases:[]},'tomato').accepted,false);
 assert.equal(scan.validateTomato(fixture('Potato',.65),'tomato',{nonTomatoConfidence:.7}).accepted,true);
 assert.equal(scan.validateTomato(fixture('Solanum lycopersicum',.9)).accepted,true);
});
